import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import WaveHeros from "@/components/WaveHeros"

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-geist-sans",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: "--font-geist-mono",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
       <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <div className="w-full h-screen flex flex-col overflow-y-hidden">
          <Header />
          <div className="container mx-auto flex flex-col grow overflow-y-auto">
            <WaveHeros/>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}